package com.mony.proyectoerp.base;

// Generated 07-may-2014 15:46:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Almacen generated by hbm2java
 *  @author Monica Saenz
 *  @version 1.0
 */
@Entity
@Table(name = "almacen", catalog = "nikages")
public class Almacen implements java.io.Serializable {

	private Integer id;
	private String nombreAlm;
	private Set<Articulo> articulos = new HashSet<Articulo>(0);

	public Almacen() {
	}

	public Almacen(String nombreAlm, Set<Articulo> articulos) {
		this.nombreAlm = nombreAlm;
		this.articulos = articulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre_alm", length = 200)
	public String getNombreAlm() {
		return this.nombreAlm;
	}

	public void setNombreAlm(String nombreAlm) {
		this.nombreAlm = nombreAlm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "almacen")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}
	/**
	 * @return Nombre del Almacen
	 */
	@Override
	public String toString(){
		return this.getNombreAlm();
	}
}
