package com.mony.proyectoerp.base;

// Generated 07-may-2014 15:46:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Articulo generated by hbm2java
 * @author Monica Saenz
 *  @version 1.0
 */
@Entity
@Table(name = "articulo", catalog = "nikages")
public class Articulo implements java.io.Serializable {

	private Integer id;
	private Almacen almacen;
	private TipoImpuesto tipoImpuesto;
	private Categoria categoria;
	private Proveedor proveedor;
	private String nombreArt;
	private Float precio;
	private String descripcion;
	private Integer stock;
	private Set<LineaDetalle> lineaDetalles = new HashSet<LineaDetalle>(0);

	public Articulo() {
	}

	public Articulo(Almacen almacen, TipoImpuesto tipoImpuesto,
			Categoria categoria, Proveedor proveedor, String nombreArt,
			Float precio, String descripcion, Integer stock,
			Set<LineaDetalle> lineaDetalles) {
		this.almacen = almacen;
		this.tipoImpuesto = tipoImpuesto;
		this.categoria = categoria;
		this.proveedor = proveedor;
		this.nombreArt = nombreArt;
		this.precio = precio;
		this.descripcion = descripcion;
		this.stock = stock;
		this.lineaDetalles = lineaDetalles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_almacen")
	public Almacen getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_impuesto")
	public TipoImpuesto getTipoImpuesto() {
		return this.tipoImpuesto;
	}

	public void setTipoImpuesto(TipoImpuesto tipoImpuesto) {
		this.tipoImpuesto = tipoImpuesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proveedor")
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@Column(name = "nombre_art", length = 200)
	public String getNombreArt() {
		return this.nombreArt;
	}

	public void setNombreArt(String nombreArt) {
		this.nombreArt = nombreArt;
	}

	@Column(name = "precio", precision = 12, scale = 0)
	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "articulo")
	public Set<LineaDetalle> getLineaDetalles() {
		return this.lineaDetalles;
	}

	public void setLineaDetalles(Set<LineaDetalle> lineaDetalles) {
		this.lineaDetalles = lineaDetalles;
	}
	/**
	 * @return Id, Nombre y Precio del articulo
	 */
	@Override
	public String toString(){
		return this.getId() + " " + this.getNombreArt() + " " +this.getPrecio();
	}
}
