package com.mony.proyectoerp.base;

// Generated 07-may-2014 15:46:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 * @author Monica Saenz
 *  @version 1.0
 */
@Entity
@Table(name = "categoria", catalog = "nikages")
public class Categoria implements java.io.Serializable {

	private Integer id;
	private String nombreCat;
	private String descripcion;
	private Set<Articulo> articulos = new HashSet<Articulo>(0);

	public Categoria() {
	}

	public Categoria(String nombreCat, String descripcion,
			Set<Articulo> articulos) {
		this.nombreCat = nombreCat;
		this.descripcion = descripcion;
		this.articulos = articulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre_cat", length = 200)
	public String getNombreCat() {
		return this.nombreCat;
	}

	public void setNombreCat(String nombreCat) {
		this.nombreCat = nombreCat;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}
	/**
	 * @return Nombre de la categoria
	 */
	@Override
	public String toString(){
		return this.getNombreCat();
	}
}
