package com.mony.proyectoerp.base;

// Generated 07-may-2014 15:46:43 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 * @author Monica Saenz
 *  @version 1.0
 */
@Entity
@Table(name = "factura", catalog = "nikages")
public class Factura implements java.io.Serializable {

	private Integer id;
	private String nombreFac;
	private String numero;
	private String serie;
	private String lugar;
	private String descripcion;
	private Date fechaEmision;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Factura() {
	}

	public Factura(String nombreFac, String numero, String serie, String lugar,
			String descripcion, Date fechaEmision, Set<Pedido> pedidos) {
		this.nombreFac = nombreFac;
		this.numero = numero;
		this.serie = serie;
		this.lugar = lugar;
		this.descripcion = descripcion;
		this.fechaEmision = fechaEmision;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre_fac", length = 100)
	public String getNombreFac() {
		return this.nombreFac;
	}

	public void setNombreFac(String nombreFac) {
		this.nombreFac = nombreFac;
	}

	@Column(name = "numero", length = 200)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "serie", length = 25)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "lugar", length = 200)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_emision", length = 10)
	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "factura")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
