package com.mony.proyectoerp.base;

// Generated 07-may-2014 15:46:43 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LineaDetalle generated by hbm2java
 * @author Monica Saenz
 *  @version 1.0
 */
@Entity
@Table(name = "linea_detalle", catalog = "nikages")
public class LineaDetalle implements java.io.Serializable {

	private Integer id;
	private Articulo articulo;
	private Pedido pedido;
	private Integer cantidad;
	private Float precio;

	public LineaDetalle() {
	}

	public LineaDetalle(Articulo articulo, Pedido pedido) {
		this.articulo = articulo;
		this.pedido = pedido;
	}

	public LineaDetalle(Articulo articulo, Pedido pedido, Integer cantidad,
			Float precio) {
		this.articulo = articulo;
		this.pedido = pedido;
		this.cantidad = cantidad;
		this.precio = precio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_articulo", nullable = false)
	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pedido", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio", precision = 12, scale = 0)
	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}
	/**
	 * @return  Nombre, Cantidad y Precio de la linea de detalle
	 */
	@Override
	public String toString(){
		return this.getArticulo().getNombreArt() + " " + this.getCantidad() + " " + this.getPrecio() + " €";
	}

}
