package com.mony.proyectoerp.base;

// Generated 07-may-2014 15:46:43 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 * @author Monica Saenz
 *  @version 1.0
 */
@Entity
@Table(name = "pedido", catalog = "nikages")
public class Pedido implements java.io.Serializable {

	private Integer id;
	private Cliente cliente;
	private Factura factura;
	private String numero;
	private String formaPago;
	private Date fechaPedido;
	private Set<LineaDetalle> lineaDetalles = new HashSet<LineaDetalle>();

	public Pedido() {
	}

	public Pedido(Cliente cliente, Factura factura, String numero,
			String formaPago, Date fechaPedido, Set<LineaDetalle> lineaDetalles) {
		this.cliente = cliente;
		this.factura = factura;
		this.numero = numero;
		this.formaPago = formaPago;
		this.fechaPedido = fechaPedido;
		this.lineaDetalles = lineaDetalles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_factura")
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@Column(name = "numero", length = 200)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "forma_pago", length = 25)
	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_pedido", length = 10)
	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<LineaDetalle> getLineaDetalles() {
		return this.lineaDetalles;
	}

	public void setLineaDetalles(Set<LineaDetalle> lineaDetalles) {
		this.lineaDetalles = lineaDetalles;
	}

}
