package com.mony.proyectoerp.base;

// Generated 07-may-2014 15:46:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Proveedor generated by hbm2java
 * @author Monica Saenz
 *  @version 1.0
 */
@Entity
@Table(name = "proveedor", catalog = "nikages", uniqueConstraints = @UniqueConstraint(columnNames = "cif"))
public class Proveedor implements java.io.Serializable {

	private Integer id;
	private String nombrePro;
	private String direccion;
	private String cif;
	private String formaPago;
	private Set<Articulo> articulos = new HashSet<Articulo>(0);

	public Proveedor() {
	}

	public Proveedor(String nombrePro, String direccion, String cif,
			String formaPago, Set<Articulo> articulos) {
		this.nombrePro = nombrePro;
		this.direccion = direccion;
		this.cif = cif;
		this.formaPago = formaPago;
		this.articulos = articulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre_pro", length = 200)
	public String getNombrePro() {
		return this.nombrePro;
	}

	public void setNombrePro(String nombrePro) {
		this.nombrePro = nombrePro;
	}

	@Column(name = "direccion", length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "cif", unique = true, length = 15)
	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "forma_pago", length = 10)
	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}
	/**
	 * @return Nombre del proveedor
	 */
	@Override
	public String toString(){
		return this.getNombrePro();
	}
}
